Implement DHCP server's management plane with local memory as storage(#102) (#111)
* dhcp: newly add dhcp service support on alcor-control-agent

Add the first edition of dhcp service with local memory as DB storage

Fixes #102

* dhcp: newly add dhcp service support on alcor-control-agent

Add the first edition of dhcp service with local memory as DB storage

Fixes #102

* dhcp: newly add dhcp service support on alcor-control-agent

Add the first edition of dhcp service with local memory as DB storage

Fixes #102

* <dhcp>: update dhcp server to use mac as the global key #102

mac address is globally unique to act as db key

#102

* Update according to PR review comments && adding mutex prection for dhcp_db#102

git commit -m

* <dhcp>: Update PR comments

#102

* Update PR comments

#102

* Update PR comments

#102

* Update PR comment

#102

* Update PR comments

#102

* Update PR comments#102

#102

* Update packet parsing for dhcp discover message#102

#102'

* Adding DHCP's specification for the project#102
#102

* Update for DHCPREQ, DHCPACK, DHCPNAK(#102)

* Update for dhcp xmit procedure #102

* Sync from Upstream

* Update dhcp openflow rule installation #102

* Create c-cpp.yml

add ci

* Update dhcp entrance calling #102

* Update c-cpp.yml

* Synchronize alcor/mizar submodule

* Remove workflows/c-cpp.yml from PR

* Update compilation error

* Update compilation error

* Update compilation error

* Update for compilation error

* Update compilation error

* Update for compilation error

* Update for dhcp unit test #102

* Update for dhcp test #102

* Update CMakeLists.txt

Update for linking error: abi:cxx11

* Update CMakeLists.txt

Update for Linking error: abi:cxx11

* Update CMakeLists.txt

Undo commit 4dde628bba63ff065cf480cd01653d3ba0983885

* Update CMakeLists.txt

Update for minimal cmake version for add_compile_definitions
https://github.com/CppMicroServices/CppMicroServices/pull/413

* Update for linking error and fix for test cases #102

* Update for packet handling issue #102

* Update for dhcp pakcet debug #102

* Update for mac address handling both as string and hex #102

* Update for in_port typo #102

* add l2/l3 dhcp packet header (#1)

Co-authored-by: gure <740684863@qq.com>